name: Java CI
on: [ push ]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
      - run: ./mvnw -B wildfly:start
      - run: ./mvnw -B wildfly:deploy
      - run: curl -s http://localhost:8080/my-app-1.0-SNAPSHOT/api/test
      - run: ./mvnw -B wildfly:undeploy
      - run: jcmd jboss-modules.jar GC.run
      - run: jcmd jboss-modules.jar GC.run
      - run: jmap -histo:all jboss-modules.jar | grep mycompany
